version: '3.8'
services:   
    postgres:
        container_name: mypostgres
        image: postgres
        restart: always
        environment:
            - 'POSTGRES_DB=${POSTGRES_DB}'
            - 'POSTGRES_USER=${POSTGRES_USER}'
            - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            - '${POSTGRES_VOLUME}:/var/lib/postgresql/data'
    
    # mysql:
    #     container_name: mysql57
    #     image: mysql:5.7
    #     restart: always
    #     environment:
    #         MYSQL_DATABASE: 'backstage'            
    #         MYSQL_USER: 'admin'            
    #         MYSQL_PASSWORD: '123456'            
    #         MYSQL_ROOT_PASSWORD: 'root'
    #     ports:
    #         - '${MYSQL_PORT}:3306'
    #     volumes:
    #         - ./data/mysql:/var/lib/mysql

    mariadb:
        container_name: mariadb
        image: mariadb:10.6.5
        restart: always
        environment:
            MARIADB_USER: 'admin'            
            MARIADB_PASSWORD: '123456'            
            MARIADB_ROOT_PASSWORD: 'root'
        ports:
            - "${MARIADB_PORT}:3306"
        volumes:
            - ./data/mariadb:/var/lib/mysql

    redis:        
        container_name: myredis
        image: redis
        restart: always
        ports:
            - '${REDIS_PORT}:6379'
        volumes:
            - ${REDIS_VOLUME}:/data
    
    mongo:
        container_name: mongodb
        image: mongo
        restart: always
        ports:
            - '${MONGO_PORT}:27017'
        volumes:
            - "${MONGO_VOLUME}:/data/db"

    rabbitmq:
        container_name: myrabbitmq
        image: rabbitmq:3-management
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}            
        ports:
            - '${RABBITMQ_PORT}:5672'
            - '${RABBITMQ_MANAGEMENT_PORT}:15672'
        volumes:
            - "${RABBITMQ_VOLUME}:/var/lib/rabbitmq/mnesia/"            

volumes:
    postgres:
    pgadmin:
    mongo:
    redis:
    portainer:
    mysql:
    rabbitmq:    
