version: '3'
services:    
    postgres:
        container_name: mypostgres
        image: postgres
        restart: always
        environment:
            - 'POSTGRES_DB=${POSTGRES_DB}'
            - 'POSTGRES_USER=${POSTGRES_USER}'
            - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            - '${POSTGRES_VOLUME}:/var/lib/postgresql/data'
        networks:
            - backend
    
    pgadmin:
        container_name: mypgadmin
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:      
            - ${PGADMIN_VOLUME}:/pgdata
        ports:
            - '${PGADMIN_PORT}:80'
        depends_on:
            - postgres
        networks:
            - backend

    mysql:
        container_name: mysql57
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'backstage'            
            MYSQL_USER: 'admin'            
            MYSQL_PASSWORD: '123456'            
            MYSQL_ROOT_PASSWORD: 'root'
        ports:            
            - '3306:3306'
        volumes:
            - mysql:/var/lib/mysql

    redis:        
        container_name: myredis
        image: redis
        restart: always
        networks:
          - backend        
        volumes:
            - ${REDIS_VOLUME}:/data
        ports:
            - '${REDIS_PORT}:6379'
    
    mongo:
        container_name: mymongo
        image: mongo
        restart: always
        volumes:
            - "${MONGO_VOLUME}:/data/db"
            - "${MONGO_ENTRYPOINT}:/docker-entrypoint-initdb.d/"
        ports:
            - ${MONGO_PORT}:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    rabbitmq:
        container_name: myrabbitmq
        image: rabbitmq:3-management
        restart: always
        volumes:
            - "${RABBITMQ_VOLUME}:/var/lib/rabbitmq/mnesia/"            
        ports:
            - ${RABBITMQ_PORT1}:5672
            - ${RABBITMQ_PORT2}:15672
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}            

    portainer:
        container_name: myportainer
        image: portainer
        restart: always
        volumes:
            - "${PORTAINER_VOLUME}:/data"
            - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
            - ${PORTAINER_PORT1}:8000
            - ${PORTAINER_PORT2}:9000

networks: 
    backend:
        driver: bridge

volumes:
    postgres:
        external: true
    pgadmin:
    mongo:
    redis:
    portainer:
    mysql:
    rabbitmq:    